### ISSUE TITLE
pycharm terminal not enabling virtual environment 

### ISSUE THREAD

**Issue by anastasia** [dhmit/urop#26]
the problem seems to be that powershell and venv don't play nice together. Fix: change from powershell to cmd.exe
settings > tools > terminal 
change shell path to be cmd.exe from powershell

**Comment by ryaanahmed** [comment]
Apparently this is a known bug in PyCharm: https://youtrack.jetbrains.com/issue/PY-22469

We need to adjust the docs to explicitly use cmd.exe in the meantime.

**Comment by ryaanahmed** [comment]
bye pycharm, we don't use you anymore!
