### ISSUE TITLE
Default Git credential manager settings changed

### ISSUE THREAD

**Issue by kmorhun** [dhmit/urop#27]
The original default settings of the Git credential manager have changed. Source: https://urop.dhmit.xyz/git/
<img width="794" alt="CredentialManager" src="https://user-images.githubusercontent.com/22576391/132913071-4dd49bd0-20f0-424c-b7b3-b9439f3f4a70.png">

**Comment by ryaanahmed** [comment]
fixed, thanks @kmorhun
