### ISSUE TITLE
Add instructions to fix PATH so that anaconda is not used.

### ISSUE THREAD

**Issue by srisi** [dhmit/urop#7]
Involves either commenting out anaconda instructions in .bash_profile (Mac) or changing settings -> ?Environment variables (for user only)? on Windows

**Comment by ryaanahmed** [comment]
> Environment variables (for user only)
Can also by system env variables if the user installed Anaconda (or an earlier version of Python) as a system-level install rather than a user-level install. (putting this here to remind me, as we encountered this also with one student)

**Comment by ryaanahmed** [comment]
dupe of #22
